site_name: Suzieq
repo_url: https://github.com/netenglabs/suzieq
python:
  install:
    - requirements: docs/requirements.txt
theme:
  name: readthedocs
  navigation_depth: 3

nav:
  - Introduction: index.md
  - Getting Started: getting_started.md
  - Gathering Data: poller.md
  - Tables: tables.md
  - GUI: gui.md
  - Suzieq Analyzer: analyzer.md
  - REST Server: rest-server.md
  - Time: time.md
  - Transports: transports.md
  - Release Notes: release-notes.md
  - Tutorials:
      - '10 things to do with Suzieq': tutorials/10things.md
      - 'How to think about verbs': tutorials/how_to_think_about_verbs.md
  - Pandas Query Examples: pandas-query-examples.md
  - Commands:
      - 'Command Introduction': commands/introduction.md
#      - arpnd: commands/arpnd.md
#      - bgp: commands/bgp.md
#      - device: commands/device.md
#      - evpnVni: commands/evpnVni.md
#      - interface: commands/interface.md
#      - lldp: commands/lldp.md
#      - mac: commands/mac.md
#      - mlag: commands/mlag.md
#      - ospf: commands/ospf.md
#      - path: commands/path.md
#      - route: commands/route.md
#      - sqpoller: commands/sqpoller.md
#      - table: commands/table.md
#      - vlan: commands/vlan.md
  - Architecture: architecture.md

#  - API:  # we'll add these later when we have reasonable docstrings that aren't so embarrassing
#      - Sqobjects: api/sqobjects.md
#      - engine: api/engine.md
#      - poller: api/poller.md
  - Service:
      - 'Configuring a service': service/service-format.md
#      - 'Interacting with devices': service/interacting_with_devices.md
#      - JSONparsing: service/parsing.md'
#      - textfsm: service/textfsm.md
  - "Developer Docs":
       - "Adding a New Network OS (NOS)": developer/adding-a-new-nos.md
       - "Service File Format": service/service-format.md
       - "Testing Philosphy and Practice": developer/testing.md
       - "Updating Test Data": developer/updating_test_data.md

#markdown_extensions: # add back when we add the API docs
#  - mkautodoc


