service: fs
type: counters
keys:
  - mountPoint
ignore-fields:
  - usedSize
  - availSize
show-fields:
  - mountPoint
  - totalSize
  - usedSize
  - usedPercent
  - device
apply:
  cumulus:
    copy: linux

  iosxr:
    version: all
    command: show filesystem location all
    textfsm: textfsm_templates/iosxr_show_fs.tfsm

  linux:
    version: all
    command: df -hT
    textfsm: textfsm_templates/fs.tfsm

  sonic:
    copy: linux

  junos-qfx:
    version: all
    command: show system storage | no-more
    textfsm: textfsm_templates/fs.tfsm

  junos-ex:
    copy: junos-qfx

  junos-mx:
    copy: junos-qfx

  junos-es:
    copy: junos-qfx

  junos-qfx10k:
    copy: junos-qfx
