service: routes
keys:
  - vrf
  - prefix
ignore-fields:
  - statusChangeTimestamp
show-fields:
  - vrf
  - prefix
  - nexthopIps
  - oifs
  - protocol
  - source
  - metric
  - ipvers
  - action

apply:
  cumulus:
    version: all
    command: ip route show table all
    textfsm: textfsm_templates/linux_routes.tfsm

  linux:
    copy: cumulus

  sonic:
    copy: cumulus

  eos:
    version: all
    command: show ip route vrf all
    normalize: 'vrfs/*:vrf/routes/*:prefix/[
        "routeType: protocol",
        "metric: metric?|0",
        "preference: preference?|0",
        "routeAction": "action?|forward",
        "hardwareProgrammed: hardwareProgrammed?|unknown",
        "vias/*/nexthopAddr: nexthopIps?|[]",
        "vias/*/interface: oifs?|[]",
        "vias/*/vtepAddr: _vtepAddr?|[]",
        "vias/*/vni: _vnis?|[]"
        ]'

  iosxe:
    version: all
    command:
      - command: show ip route vrf *
        textfsm: textfsm_templates/iosxe_show_route.tfsm
      - command: show ipv6 route vrf *
        textfsm: textfsm_templates/iosxe_show_route.tfsm
  
  iosxr:
    version: all
    command:
      - command: show route vrf default afi-all unicast
        textfsm: textfsm_templates/iosxr_show_route.tfsm
      - command: show route vrf all afi-all unicast
        textfsm: textfsm_templates/iosxr_show_route.tfsm

  ios:
    copy: iosxe
  
  junos-qfx:
    version: all
    command:
      - command: show route | display json | no-more
        normalize: 'route-information/[0]/route-table/*:table-name:vrf/rt/*/[
        "rt-destination/[0]/data: prefix",
        "rt-prefix-length/[0]/data: _rtlen?|0",
        "rt-entry/[0]/protocol-name/[0]/data: protocol",
        "rt-entry/[0]/preference/[0]/data: preference?|0",
        "rt-entry/[0]/age/[0]/attributes: statusChangeTimestamp?|",
        "rt-entry/[0]/metric/[0]/data: metric?|0",
        "rt-entry/[0]/active-tag/[0]/data: _activeTag",
        "rt-entry/[0]/as-path/[0]/data: asPathList?|[]",
        "rt-entry/[0]/validation-state/[0]/data: validState?|",
        "rt-entry/[0]/nh/[*]/to/[0]/data: nexthopIps",
        "rt-entry/[0]/nh/[*]/via/[0]/data: oifs",
        "rt-entry/[0]/nh/[0]/nh-local-interface/[0]/data: _localif?|",
        "rt-entry/[0]/nh-type/[0]/data: action?|forward",
        "rt-entry/[0]/rt-tag/[0]/data: routeTag?|",
        "hardwareProgrammed: hardwareProgrammed?|unknown",
        ]'

      - command: show evpn ip-prefix-database | display json | no-more
        normalize: 'evpn-ip-prefix-database-information/evpn-pfxdb-l3-context/*:context-name:vrf|evpn-pfxdb-evpn-ip-table/[0]/evpn-pfxdb-evpn-ip-entry/*/[
        "entry-prefix/[0]/data: prefix",
        "evpn-pfxdb-evpn-ip-adv/[0]/adv-bgp-nexthop/[0]/data: _vtepAddr"
        ]'

  junos-ex:
    copy: junos-qfx

  junos-mx:
    copy: junos-qfx

  junos-es:
    copy: junos-qfx

  nxos: 
    version: all
    command: show ip route vrf all | json native
    normalize: 'TABLE_vrf/ROW_vrf/*:vrf-name-out:vrf|TABLE_addrf/ROW_addrf/TABLE_prefix/ROW_prefix/*?/[
    "ipprefix: prefix",
    "TABLE_path/ROW_path/[0]?/clientname: protocol?|",
    "TABLE_path/ROW_path/[*]?/pref: preference?|0",
    "TABLE_path/ROW_path/[*]?/metric: metric?|0",
    "TABLE_path/ROW_path/[*]?/ifname: oifs?|",
    "TABLE_path/ROW_path/[*]?/uptime: statusChangeTimestamp?|",
    "TABLE_path/ROW_path/[*]?/ipnexthop: nexthopIps?|",
    "TABLE_path/ROW_path/[*]?/nexthop-vrf-name: _nexthopVrf?|",
    "hardwareProgrammed: inHardware?|unknown",
    "TABLE_path/ROW_path/[*]?/type: _routeAction?|forward",
    "TABLE_path/ROW_path/[*]?/tag: routeTag?|",
    ]'
