service: arpnd
keys:
  - ipAddress
  - oif

show-fields:
  - ipAddress
  - oif
  - macaddr
  - state
  - remote

apply:
  cumulus:
    version: all
    command: ip neigh show
    textfsm: textfsm_templates/linux_ipneigh.tfsm

  linux:
    copy: cumulus

  eos:
    version: all
    command: show arp vrf all
    normalize: 'vrfs/*:vrf/ipV4Neighbors/*/[
    "hwAddress: macaddr",
    "address: ipAddress",
    "interface: oif",
    "interface: origIfname",
    "state: state?|reachable",
    "offload: remote?|False",
    ]'

  junos:
    version: all
    command: show arp | display json
    normalize: 'arp-table-information/[0]/arp-table-entry/*/[
    "mac-address/[0]/data: macaddr",
    "ip-address/[0]/data: ipAddress",
    "interface-name/[0]/data: oif",
    "interface-name/[0]/data: origIfname",
    "arp-table-entry-flags: flags",
    "offload: remote?|False",
    ]'

  nxos:
    version: all
    command:
      - command: show ip arp detail vrf all | json
        normalize: 'TABLE_vrf/ROW_vrf/*:vrf-name-out:vrf|TABLE_adj/ROW_adj/*?/[
        "intf-out: oif",
        "intf-out: origIfname",
        "ip-addr-out: ipAddress",
        "flags: flags",
        "mac: macaddr"
        ]'

      - command: show ipv6 neighbor detail | json
        normalize: 'TABLE_vrf/ROW_vrf/*:vrf-name-out:vrf|TABLE_afi/ROW_afi/*?/[
        "intf-out: oif",
        "intf-out: origIfname",
        "ip-addr-out: ipAddress",
        "flags: flags",
        "mac: macaddr"
        ]'
      
