
service: bgp
ignore-fields:
  - lastDownTime
  - estdTime
keys:
  - vrf
  - peer
show-fields:
  - vrf
  - peer
  - peerHostname
  - state
  - asn
  - peerAsn
  - v4PfxRx
  - estdTime
  - numChanges

apply:
  eos:
    version: all
    command: show ip bgp neighbors vrf all
    normalize: 'vrfs/*/peerList/*/[
        "asn: peerAsn?|0", 
        "localAsn: asn?|0", 
        "updateSource: source",
        "peerHostname: peerHostname?|",
        "peerAddress: peer",
        "peerAddress: origPeer",
        "peerAddress: peerIP?|",
        "vrf: vrf",
        "maintenance: maintenance", 
        "establishFailHint: reason",
        "notificnReason: notificnReason?|",
        "lastErrorTimeInfo/time: lastDownTime?|0",
        "prefixesReceived: v4PfxRx?|0",
        "prefixesSent: v4PfxTx?|0",
        "v6PrefixesReceived: v6PfxRx?|0",
        "v6PrefixesSent: v6PfxTx?|0",
        "receivedUpdates: updatesRx?|0",
        "bgpSoftReconfigInbound: softConfigIn?|",
        "routeMapInfo/outboundIpv4Uni: v4EgressRmap",
        "routeMapInfo/outboundIpv6Uni: v6EgressRmap",
        "routeMapInfo/outboundEvpn: evpnEgressRmap",
        "routeMapInfo/inboundIpv4Uni: v4IngressRmap",
        "routeMapInfo/inboundIpv6Uni: v6IngressRmap",
        "routeMapInfo/inboundEvpn: evpnIngressRmap",
        "sentUpdates: updatesTx?|0",
        "routerId: peerRouterId",
        "localRouterId: routerId",
        "holdTime": "holdTime?|0",
        "keepaliveTime": "keepaliveTime?|0",
        "establishedTime: estdTime?|0",
        "establishedTransitions: numChanges?|0",
        "updateSource: updateSource?|",
        "v4Enabled: v4Enabled?|True",
        "v6Enabled: v6Enabled?|False",
        "evpnEnabled: evpnEnabled?|False",
        "v4Advertised: v4Advertised?|False",
        "v6Advertised: v6Advertised?|False",
        "evpnAdvertised: evpnAdvertised?|False",
        "v4Received: v4Received?|False",
        "v6Received: v6Received?|False",
        "evpnReceived: evpnReceived?|False",
        "bfdState: bfdStatus?|disabled",
        "v6BestEcmpPaths: v6EcmpEnabled?|0",
        "v4BestEcmpPaths: v4EcmpEnabled?|0",
        "state: state?Established|NotEstd"]'
  cumulus:
    version: all
    command: net show bgp vrf all neighbor json
    normalize: '*:vrf/*:peer/[
        "remoteAs: peerAsn",
        "localAs: asn",
        "lastResetDueTo: reason?|",
        "lastNotificationReason: notificnReason?|",
        "lastResetTimerMsecs: lastDownTime?|0",
        "addressFamilyInfo/IPv4 Unicast/acceptedPrefixCounter: v4PfxRx?|0",
        "addressFamilyInfo/IPv6 Unicast/acceptedPrefixCounter: v6PfxRx?|0",
        "addressFamilyInfo/L2VPN EVPN/acceptedPrefixCounter: evpnPfxRx?|0",
        "addressFamilyInfo/L2VPN EVPN/advertiseAllVnis: advertiseAllVnis?|False",
        "addressFamilyInfo/L2VPN EVPN/commAttriSentToNbr: evpnSendCommunity?|",
        "addressFamilyInfo/L2VPN EVPN/unchangedNextHopPropogatedToNbr: nhUnchanged?|False",
        "addressFamilyInfo/l2vpnEvpn/advertiseAllVnis: advertiseAllVnis?|advertiseAllVnis",
        "addressFamilyInfo/l2vpnEvpn/unchangedNextHopPropogatedToNbr: nhUnchanged?|nhUnchanged",
        "addressFamilyInfo/l2vpnEvpn/commAttriSentToNbr: evpnSendCommunity?|",
        "addressFamilyInfo/ipv4Unicast/acceptedPrefixCounter: v4PfxRx?|v4PfxRx",
        "addressFamilyInfo/ipv6Unicast/acceptedPrefixCounter: v6PfxRx?|v6PfxRx",
        "addressFamilyInfo/l2vpnEvpn/acceptedPrefixCounter: evpnPfxRx?|evpnPfxRx",
        "addressFamilyInfo/ipv4Unicast/sentPrefixCounter: v4PfxTx?|0",
        "addressFamilyInfo/ipv6Unicast/sentPrefixCounter: v6PfxTx?|0",
        "addressFamilyInfo/l2vpnEvpn/sentPrefixCounter: evpnPfxTx?|0",
        "addressFamilyInfo/ipv4Unicast/routeReflectorClient: rrclient?|False",
        "addressFamilyInfo/ipv4Unicast/defaultSent: v4DefaultSent?|False",
        "addressFamilyInfo/ipv6Unicast/defaultSent: v6DefaultSent?|False",
        "addressFamilyInfo/l2vpnEvpn/defaultSent: evpnDefaultSent?|False",
        "addressFamilyInfo/ipv4Unicast/routeMapForIncomingAdvertisements: v4IngressRmap?|",
        "addressFamilyInfo/ipv4Unicast/routeMapForOutgoingAdvertisements: v4EgressRmap?|",
        "addressFamilyInfo/ipv6Unicast/routeMapForIncomingAdvertisements: v6IngressRmap?|",
        "addressFamilyInfo/ipv6Unicast/routeMapForOutgoingAdvertisements: v6EgressRmap?|",
        "addressFamilyInfo/l2vpnEvpn/routeMapForIncomingAdvertisements: evpnIngressRmap?|",
        "addressFamilyInfo/l2vpnEvpn/routeMapForOutgoingAdvertisements: evpnEgressRmap?|",
        "messageStats/updatesSent: updatesTx",
        "messageStats/updatesRecv: updatesRx",
        "remoteRouterId: peerRouterId",
        "localRouterId: routerId",
        "bgpState: state?Established|NotEstd",
        "bgpTimerUpEstablishedEpoch: estdTime*1000",
        "connectionsEstablished: numChanges",
        "connectionsDropped: numChanges+numChanges",
        "bgpTimerHoldTimeMsecs: holdTime/1000",
        "bgpTimerKeepAliveIntervalMsecs: keepaliveTime/1000",
        "minBtwnAdvertisementRunsTimerMsecs: mrai/1000",
        "peerBfdInfo/status: bfdStatus?|disabled",
        "neighborCapabilities/extendedNexthop": extnhEnabled",
        "neighborCapabilities/hostName/rcvHostName: peerHostname?|",
        "neighborCapabilities/multiprotocolExtensions/ipv4Unicast/advertisedAndReceived: v4Enabled?|False",
        "neighborCapabilities/multiprotocolExtensions/l2vpnEvpn/advertisedAndReceived: evpnEnabled?|False",
        "neighborCapabilities/multiprotocolExtensions/ipv6Unicast/advertisedAndReceived: v6Enabled?|False",
        "neighborCapabilities/multiprotocolExtensions/ipv4Unicast/advertised: v4Advertised?|False",
        "neighborCapabilities/multiprotocolExtensions/l2vpnEvpn/advertised: evpnAdvertised?|False",
        "neighborCapabilities/multiprotocolExtensions/ipv6Unicast/advertised: v6Advertised?|False",
        "neighborCapabilities/multiprotocolExtensions/ipv4Unicast/received: v4Received?|False",
        "neighborCapabilities/multiprotocolExtensions/l2vpnEvpn/received: evpnReceived?|False",
        "neighborCapabilities/multiprotocolExtensions/ipv6Unicast/received: v6Received?|False",
        "neighborCapabilities/multiprotocolExtensions/IPv4 Unicast/advertisedAndReceived: v4Enabled?|v4Enabled",
        "neighborCapabilities/multiprotocolExtensions/L2VPN EVPN/advertisedAndReceived: evpnEnabled?|evpnEnabled",
        "neighborCapabilities/multiprotocolExtensions/IPv6 Unicast/advertisedAndReceived: v6Enabled?|v6Enabled",
        "neighborCapabilities/multiprotocolExtensions/IPv4 Unicast/advertised: v4Advertised?|v4Advertised",
        "neighborCapabilities/multiprotocolExtensions/L2VPN EVPN/advertised: evpnAdvertised?|evpnAdvertised",
        "neighborCapabilities/multiprotocolExtensions/IPv6 Unicast/advertised: v6Advertised?|v6Advertised",
        "neighborCapabilities/multiprotocolExtensions/IPv4 Unicast/received: v4Received?|v4Received",
        "neighborCapabilities/multiprotocolExtensions/L2VPN EVPN/received: evpnReceived?|evpnReceived",
        "neighborCapabilities/multiprotocolExtensions/IPv6 Unicast/received: v6Received?|v6Received",
        "hostLocal: updateSource?|",
        "hostForeign: peerIP?|"]'
  linux:
      version: all
      command: sudo vtysh -c "show bgp vrf all neighbors json"
      normalize: '*:vrf/*:peer/[
        "remoteAs: peerAsn",
        "localAs: asn",
        "lastResetDueTo: reason?|",
        "lastNotificationReason: notificnReason?|",
        "lastResetTimerMsecs: lastDownTime?|0",
        "addressFamilyInfo/IPv4 Unicast/acceptedPrefixCounter: v4PfxRx?|0",
        "addressFamilyInfo/IPv6 Unicast/acceptedPrefixCounter: v6PfxRx?|0",
        "addressFamilyInfo/L2VPN EVPN/acceptedPrefixCounter: evpnPfxRx?|0",
        "addressFamilyInfo/L2VPN EVPN/advertiseAllVnis: advertiseAllVnis?|False",
        "addressFamilyInfo/L2VPN EVPN/commAttriSentToNbr: evpnSendCommunity?|",
        "addressFamilyInfo/L2VPN EVPN/unchangedNextHopPropogatedToNbr: nhUnchanged?|False",
        "addressFamilyInfo/l2vpnEvpn/advertiseAllVnis: advertiseAllVnis?|advertiseAllVnis",
        "addressFamilyInfo/l2vpnEvpn/unchangedNextHopPropogatedToNbr: nhUnchanged?|nhUnchanged",
        "addressFamilyInfo/l2vpnEvpn/commAttriSentToNbr: evpnSendCommunity?|",
        "addressFamilyInfo/ipv4Unicast/acceptedPrefixCounter: v4PfxRx?|v4PfxRx",
        "addressFamilyInfo/ipv6Unicast/acceptedPrefixCounter: v6PfxRx?|v6PfxRx",
        "addressFamilyInfo/l2vpnEvpn/acceptedPrefixCounter: evpnPfxRx?|evpnPfxRx",
        "addressFamilyInfo/ipv4Unicast/routeReflectorClient: rrclient?|False",
        "addressFamilyInfo/ipv4Unicast/defaultSent: v4DefaultSent?|False",
        "addressFamilyInfo/ipv6Unicast/defaultSent: v6DefaultSent?|False",
        "addressFamilyInfo/l2vpnEvpn/defaultSent: evpnDefaultSent?|False",
        "addressFamilyInfo/ipv4Unicast/sentPrefixCounter: v4PfxTx?|0",
        "addressFamilyInfo/ipv6Unicast/sentPrefixCounter: v6PfxTx?|0",
        "addressFamilyInfo/l2vpnEvpn/sentPrefixCounter: evpnPfxTx?|0",
        "addressFamilyInfo/ipv4Unicast/routeMapForIncomingAdvertisements: v4IngressRmap?|",
        "addressFamilyInfo/ipv4Unicast/routeMapForOutgoingAdvertisements: v4EgressRmap?|",
        "addressFamilyInfo/ipv6Unicast/routeMapForIncomingAdvertisements: v6IngressRmap?|",
        "addressFamilyInfo/ipv6Unicast/routeMapForOutgoingAdvertisements: v6EgressRmap?|",
        "addressFamilyInfo/l2vpnEvpn/routeMapForIncomingAdvertisements: evpnIngressRmap?|",
        "addressFamilyInfo/l2vpnEvpn/routeMapForOutgoingAdvertisements: evpnEgressRmap?|",
        "messageStats/updatesSent: updatesTx",
        "messageStats/updatesRecv: updatesRx",
        "remoteRouterId: peerRouterId",
        "localRouterId: routerId",
        "bgpState: state?Established|NotEstd",
        "bgpTimerUpEstablishedEpoch: estdTime*1000",
        "connectionsEstablished: numChanges",
        "connectionsDropped: numChanges+numChanges",
        "bgpTimerHoldTimeMsecs: holdTime/1000",
        "bgpTimerKeepAliveIntervalMsecs: keepaliveTime/1000",
        "minBtwnAdvertisementRunsTimerMsecs: mrai/1000",
        "peerBfdInfo/status: bfdStatus?|disabled",
        "neighborCapabilities/hostName/rcvHostName: peerHostname?|",
        "neighborCapabilities/multiprotocolExtensions/ipv4Unicast/advertisedAndReceived: v4Enabled?|False",
        "neighborCapabilities/multiprotocolExtensions/l2vpnEvpn/advertisedAndReceived: evpnEnabled?|False",
        "neighborCapabilities/multiprotocolExtensions/ipv6Unicast/advertisedAndReceived: v6Enabled?|False",
        "neighborCapabilities/multiprotocolExtensions/ipv4Unicast/advertised: v4Advertised?|False",
        "neighborCapabilities/multiprotocolExtensions/l2vpnEvpn/advertised: evpnAdvertised?|False",
        "neighborCapabilities/multiprotocolExtensions/ipv6Unicast/advertised: v6Advertised?|False",
        "neighborCapabilities/multiprotocolExtensions/ipv4Unicast/received: v4Received?|False",
        "neighborCapabilities/multiprotocolExtensions/l2vpnEvpn/received: evpnReceived?|False",
        "neighborCapabilities/multiprotocolExtensions/ipv6Unicast/received: v6Received?|False",
        "neighborCapabilities/multiprotocolExtensions/IPv4 Unicast/advertisedAndReceived: v4Enabled?|v4Enabled",
        "neighborCapabilities/multiprotocolExtensions/L2VPN EVPN/advertisedAndReceived: evpnEnabled?|evpnEnabled",
        "neighborCapabilities/multiprotocolExtensions/IPv6 Unicast/advertisedAndReceived: v6Enabled?|v6Enabled",
        "neighborCapabilities/multiprotocolExtensions/IPv4 Unicast/advertised: v4Advertised?|v4Advertised",
        "neighborCapabilities/multiprotocolExtensions/L2VPN EVPN/advertised: evpnAdvertised?|evpnAdvertised",
        "neighborCapabilities/multiprotocolExtensions/IPv6 Unicast/advertised: v6Advertised?|v6Advertised",
        "neighborCapabilities/multiprotocolExtensions/IPv4 Unicast/received: v4Received?|v4Received",
        "neighborCapabilities/multiprotocolExtensions/L2VPN EVPN/received: evpnReceived?|evpnReceived",
        "neighborCapabilities/multiprotocolExtensions/IPv6 Unicast/received: v6Received?|v6Received",
        "hostLocal: updateSource?|",
        "hostForeign: peerIP?|"]'
  sonic:
    copy: linux

  nxos:
    version: all
    command:
      - command: show bgp all neighbors vrf all | json
        normalize: 'TABLE_neighbor/ROW_neighbor/*?/[
        "neighbor: peer",
        "neighbor: origPeer",
        "ipv4prefixneighbor: _dynPeer",
        "remoteas: peerAsn?|0",
        "remote-id: peerRouterId",
        "vrf: vrf?|default",
        "sourceif: ifname",
        "passiveonly: passive?|False",
        "state: state?Established|NotEstd",
        "holdtime: holdTime?|0",
        "keepalivetime: keepalivetime?|0",
        "connsestablished: numChanges?|0",
        "connsdropped: numChanges+numChanges",
        "elapsedtime: estdTime?|",
        "resetreason: reason",
        "peerresetreason: "notificnReason?|",
        "TABLE_af/ROW_af/[*]?/TABLE_saf/ROW_saf/af-name: afiSafi",
        "TABLE_af/ROW_af/[*]?/TABLE_saf/ROW_saf/af-recvd: afRcvd",
        "TABLE_af/ROW_af/[*]?/TABLE_saf/ROW_saf/af-advertised: afAdvertised",
        "capextendednhadvertised: extnhAdvertised",
        "capextendednhrecvd: extnhReceived",
        "updatessent: updatesTx?|0",
        "updatesrecvd: updatesRx?|0",
        "TABLE_peer/ROW_peer/[*]?/peer: _dynamicPeers",
        "activepeers: _activePeers",
        "maxconcurrentpeers: _maxconcurrentpeers",
        "TABLE_peraf/ROW_peraf/[*]?/TABLE_persaf/ROW_persaf/per-af-name: afiPrefix",
        "TABLE_peraf/ROW_peraf/[*]?/TABLE_persaf/ROW_persaf/pfxrecvd: pfxRcvd",
        "TABLE_peraf/ROW_peraf/[*]?/TABLE_persaf/ROW_persaf/pfxsent: pfxSent",
        "TABLE_peraf/ROW_peraf/[*]?/TABLE_persaf/ROW_persaf/sendextcommunity: extendComm",
        "TABLE_peraf/ROW_peraf/[*]?/TABLE_persaf/ROW_persaf/sendextcommunity: sendComm",
        "TABLE_peraf/ROW_peraf/[0]?/TABLE_persaf/ROW_persaf/rrconfigured: rrclient?|False",
        "TABLE_peraf/ROW_peraf/[0]?/TABLE_persaf/ROW_persaf/firstconvgtime: _firstconvgtime",
        "TABLE_peraf/ROW_peraf/[*]?/TABLE_persaf/ROW_persaf/defaultoriginate: defaultOrig?|",
        "localaddr: updateSource?|",
        "remoteaddr: peerIP?|",
        "entry-type: _entryType?|neighbors",
        ]'

      - command: show bgp all summary vrf all | json
        normalize: 'TABLE_vrf/ROW_vrf/*?/[
        "vrf-name-out: vrf",
        "vrf-name-out: peer",
        "vrf-local-as: asn",
        "vrf-router-id: routerId",
        "entry-type: _entryType?|summary"
        ]'

  junos-qfx:
    version: all
    command:
      - command: show bgp summary | display json
        normalize: 'bgp-information/bgp-peer/*/[
        "peer-address/[0]/data: peer",
        "elapsed-time/[0]/attributes: estdTime?|",
        "vrf: vrf?|default",
        "entry_type: _entryType?|summary",
        ]'

      - command: "show bgp neighbor | display json"
        normalize: 'bgp-information/[0]/bgp-peer/*/[
        "bgp-rib/[*]/advertised-prefix-count/[0]/data: pfxTxList",
        "peer-address/[0]/data: peerIP",
        "peer-address/[0]/data: peer",
        "peer-as/[0]/data: peerAsn?|0",
        "local-address/[0]/data: updateSource",
        "local-as/[0]/data: asn",
        "peer-state/[0]/data: state?Established|NotEstd",
        "last-error/[0]/data: reason",
        "bgp-option-information/[0]/export-policy/[0]/data: v4EgressRmap",
        "bgp-option-information/[0]/import-policy/[0]/data: v4IngressRmap",
        "bgp-option-information/[0]/holdtime/[0]/data: holdTime?|0",
        "bgp-option-information/[0]/address-families/[0]/data: afiSafiAdvList?|",
        "nlri-type-session/[0]/data: afiSafiEnabledList?|",
        "nlri-type-peer/[0]/data: afiSafiRcvList?|",
        "bgp-error/[0]/name/[0]/data: notificnReason?|",
        "flap-count/[0]/data: numChanges?|0",
        "peer-id/[0]/data: peerRouterId",
        "local-id/[0]/data: routerId",
        "keepalive-interval/[0]/data: keepaliveTime?|0",
        "bgp-bfd/[0]/bfd-operational-state/[0]/data: bfdStatus",
        "local-interface-name/[0]/data: ifname",
        "bgp-rib/[*]/received-prefix-count/[0]/data: pfxRxList?|",
        "bgp-rib/[*]/name/[0]/data: pfxType",
        "bgp-traffic/[0]/input-updates/[0]/data: updatesRx?|0",
        "output-updates/[0]/data: updatesTx?|0",
        "vrf: vrf?|default",
        "entry_type: _entryType?|neighbors",
        ]'

  junos-ex:
    copy: junos-qfx

  junos-mx:
    copy: junos-qfx
