service: interfaces
keys:
  - ifname

show-fields:
  - ifname
  - state
  - type
  - mtu
  - master
  - ipAddressList
  - ip6AddressList

apply:
  cumulus:
    version: all
    command: sudo vtysh -c "show int vrf all"; ip -d address show
    textfsm: textfsm_templates/cl_interfaces.tfsm

  eos:
    version: all
    command: show interfaces
    # bunch of fields need code fixups. see service file
    normalize: 'interfaces/*/[
    "name: ifname",
    "mtu: mtu?|0",
    "description: description",
    "physicalAddress: macaddr",
    "bandwidth: speed?|0",
    "srcIpAddr: srcVtepIp",
    "vlanToVniMap/*:vlan?|0",
    "vlanToVniMap/*/vni: vni?|0",
    "lineProtocolStatus: state",
    "hardware: type",
    "forwardingModel: forwardingModel",
    "linkStatusChanges: numChanges?|0",
    "lastStatusChangeTimeStamp": statusChangeTimestamp",
    "fallbackEnabled: lacpBypass?|False",
    "interfaceMembership: master?|",
    "interfaceAddress: ipAddressList?|[]",
    "interfaceAddressIP6: ip6AddressList?|[]",
    ]'

  linux:
    version: all
    command: ip -d address show
    textfsm: textfsm_templates/linux_ipaddr.tfsm
  
  junos:
    version: all
    command: show interface | display json
    normalize: 'interface-information/[0]/physical-interface/*/[
    "oper-status/[0]/data: state",
    "speed/[0]/data: speed?|0",
    "name/[0]/data: ifname",
    "name/[0]/data: origIfname",
    "description/[0]/data: description",
    "if-type/[0]/data: type",
    "link-level-type/[0]/data: type?|type",
    "mtu/[0]/data: mtu?|0",
    "current-physical-address/[0]/data: macaddr",
    "interface-flapped/[0]/data: statusChangeTimestamp",
    "logical-interface/[0]/encapsulation/[0]/data: master?Ethernet-Bridge|",
    "logical-interface/[*]/irb-domain/[0]/irb-bridge/[0]/data: vlanName",
    "logical-interface/[*]/name/[0]/data: logicalIfname",
    "logical-interface/[*]/if-config-flags: logicalIfflags",
    "logical-interface/[*]/address-family: afi",
    ]'
    

  nxos:
    version: all
    command:
      - command: show interface brief | json
        normalize: 'TABLE_interface/ROW_interface/*/[
        "interface: ifname",
        "state: state",
        "svi_admin_state: state?|state",
        "speed: speed?|0",
        "mtu: mtu?|0",
        "portmode: _portmode?|routed",
        "type: type?|",
        "vlan: vlan",
        "state_rsn_desc: reason",
        "svi_reason_desc: reason?|reason",
        ]'

      - command: show ip interface | json
        normalize: 'TABLE_intf/ROW_intf/*/[
        "vrf-name-out: vrf",
        "intf-name: ifname",
        "proto-state: state",
        "prefix: ipAddressList",
        "masklen: _maskLen",
        "mtu: mtu",
        "unnum-intf: _unnum_intf?|",
        "TABLE_unnuminf/ROW_unnuminf/unnum-child-inf: _child_intf?|[]",
        "TABLE_secondary_address/ROW_secondary_address/[*]?/prefix1: _secIPs",
        "TABLE_secondary_address/ROW_secondary_address/[*]?/masklen1: _secmasklens",
        ]'

      - command: show ipv6 interface | json
        normalize: 'TABLE_intf/ROW_intf/*?/[
        "vrf-name-out: vrf",
        "intf-name: ifname",
        "TABLE_addr/ROW_addr/[*]?/addr: ip6AddressList",
        "linklocal-addr: _linklocal"
        ]'
