service: macs
keys:
  # We deliberately don't have VLAN as a key field. We add an artificial
  # key field in the schema and during data cleanup to handle EVPN HER
  # entries among other cases where the VLAN doesn't disambiguate MAC addr.
  - macaddr

show-fields:
  - vlan
  - macaddr
  - oif
  - remoteVtepIp
  - bd
  - flags

apply:
  cumulus:
    version: all
    command: /sbin/bridge fdb show
    textfsm: textfsm_templates/linux_fdb.tfsm

  linux:
    copy: cumulus

  sonic:
    copy: cumulus

  junos-qfx:
    version: all
    command: show ethernet-switching table detail | display json
    normalize: 'l2ng-l2ald-rtb-macdb/[0]/l2ng-l2ald-mac-entry-vlan/*/[
    "l2ng-l2-mac-address/[0]/data: macaddr",
    "l2ng-l2-vlan-id/[0]/data: vlan?|0",
    "l2ng-l2-mac-logical-interface/[0]/data: oif",
    "l2ng-l2-active-source/[0]/data: remoteVtepIp?|",
    "l2ng-l2-mac-entry-flags/[0]/data: flags"
    ]'


  junos-ex:
    copy: junos-qfx

  junos-mx:
    version: all
    command: show vpls mac-table
    textfsm: textfsm_templates/junos_vpls_mac.tfsm

  nxos:
    version: all
    command: show mac address-table | json
    normalize: 'TABLE_mac_address/ROW_mac_address/*?/[
    "disp_mac_addr: macaddr",
    "disp_port: oif?|",
    "disp_vlan: vlan?|0",
    "disp_is_secure: isSecure?|",
    "disp_type: flags",
    ]'

  eos:
    command: show mac-address-table unicast
    normalize: 'unicastTable/tableEntries/*/[
    "macAddress: macaddr",
    "vlanId: vlan?|0",
    "entryType: flags",
    "interface: oif",
    ]'
