service: mlag
show-fields:
  - systemId
  - state
  - peerAddress
  - role
  - peerLink
  - mlagDualPortsCnt
  - mlagSinglePortsCnt
  - mlagErrorPortsCnt
apply:
  cumulus:
    version: all
    command: 'if [ -f "/etc/default/clagd" ]; then net show clag json; else echo {}; fi'
    normalize: '[
    "status/peerAlive: state",
    "status/sysMac: systemId",
    "status/peerIp: peerAddress",
    "status/ourRole: role",
    "status/peerRole: peerRole",
    "status/peerId: peerMacAddress",
    "status/peerIf: peerLink",
    "peerLinkStatus: peerLinkStatus?|NA",
    "status/backupActive: backupActive?|False",
    "status/backupIp: backupIP",
    "status/backupReason: backupReason?|",
    "status/linklocal: usesLinkLocal?|False",
    "status/domainId: domainId?|NA",
    "status/vxlanAnycast: vtepIP",
    "clagIntfs: mlagInterfacesList",
    ]'
  eos:
    version: all
    command: show mlag detail
    normalize: '[
    "state: state?|disabled",
    "systemId: systemId",
    "peerAddress: peerAddress",
    "status/peerRole: peerRole",
    "detail/peerMacAddress: peerMacAddress",
    "peerLinkStatus: peerLinkStatus",
    "dualPrimaryDetectionState: backupActive?True|False",
    "backupIP: backupIP?|NA",
    "domainId: domainId",
    "linklocal: usesLinkLocal?|False",
    "vxlanAnycast: vtepIP?|NA",
    "portsErrDisabled: portsErrDisabled",
    "detail/mlagState: role",
    "mlagPorts/Disabled: mlagErrorPortsCnt?|0",
    "mlagPorts/Active-partial: mlagSinglePortsCnt?|0",
    "mlagPorts/Active-full: mlagDualPortsCnt?|0",
    "mlagPorts/Inactive: mlagErrorPortsCnt+mlagErrorPortsCnt",
    "configSanity: configSanity?|"]'
  nxos:
    version: all
    command:
      - command: show vpc | json
        normalize: '[
        "vpc-domain-id: systemId",
        "vpc-role: role",
		    "vpc-peer-consistency: _globalConsistency", 
        "vpc-per-vlan-peer-consistency: _globalVlanConsistency", 
        "vpc-type-2-consistency: _globalType2Consistency ",
        "TABLE_peerlink/ROW_peerlink/peerlink-ifindex: peerLink",
        "TABLE_peerlink/ROW_peerlink/peer-link-port-state: peerLinkStatus",
        "TABLE_vpc/ROW_vpc/[*]?/vpc-ifindex: _portList",
        "TABLE_vpc/ROW_vpc/[*]?/vpc-port-state: _portStateList",
        "TABLE_vpc/ROW_vpc/[*]?/vpc-thru-peerlink: _forwardViaPeerLinkList",
        "TABLE_vpc/ROW_vpc/[*]?/vpc-consistency: _portConfigSanityList",
        ]'

      - command: show vpc orphan-ports | json
        normalize: '[
        "TABLE_orphan_ports/ROW_orphan_ports/[*]?/vpc-orphan-ports: _orphanPortList",
        ]'

      - command: show vpc peer-keepalive | json
        normalize: '[
        "vpc-keepalive-dest: peerAddress",
        ]'

      - command: show vpc role | json
        normalize: '[
        "vpc-peer-status: state",
        "vpc-peer-system-mac: peerMacAddress",
        ]'

      - command: show nve interface nve 1 | json
        normalize: 'TABLE_nve_if/ROW_nve_if/*?/[
        "secondary-ip: vtepIP",
        ]'
